container:
  image: node:latest
test_task:
  node_modules_cache:
    folder: node_modules
    populate_script: npm i
  script: npm run test

deploy_task:
  depends_on:
    - check
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package.json
    populate_script: npm i
  
  env:
    CSUMB_FEEDBACK_KEY: ENCRYPTED[5941e37fd78bc922e10214b5b57887f5ff82807671bdd282f9531d9d7b40de5c968e97e1d2f36cccc7416cc08066d7d7]
    CSUMB_HOME_CONTENTFUL_SPACE: ENCRYPTED[0c9450f6dae892b491ba9a94cbcfc70f3a51709ac40ca05ae4d9cae05d50bf13c8d05ba5eb722b5a2c562901cee03538]
    CSUMB_HOME_CONTENTFUL_TOKEN: ENCRYPTED[6e38327e84ccc4b251daf9f9036e34cd0dc011772899bcd4e8a8c50bba0b5b78d20b8e2b6d370448e843fc8bff315bc0]
    CSUMB_NAV_CONTENTFUL_SPACE: ENCRYPTED[484f4a40d372bd3741eb974136cd76594b2a309d8c76a434b3573011c2596c9d15269ba33ed67aedefbe2a3d502fbdce]
    CSUMB_NAV_CONTENTFUL_TOKEN: ENCRYPTED[ddace2691cae8b1cb4fe36a657c206896e1f03ceaee546e66d1bb535ba345c33c8d129b247d218d4626f5223ced7d78a]
    FIREBASE_TOKEN: ENCRYPTED[4c4d209d91abe58092d022f26cab87e43a712fe65f0fac74c3551aa06b5ce76a3bfbf86043a1f02cad89f743f5b2d67a]
    GITHUB_TOKEN: ENCRYPTED[de199f8d18f3fb0958784265ae5c138de547dc3a17bd2bdd92f788e1855a35256c76f3f2666769c0c2bc380377725234]
  script: 
    - ./node_modules/.bin/grunt
    - ./node_modules/.bin/gatsby build
    - npm run directoryJson
    - npm run configFirebase
    - npm run canary
    - ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN -P $CIRRUS_BRANCH

storybook_task:
  node_modules_cache:
    folder: node_modules
    populate_script: npm i
  env:
    GITHUB_TOKEN: ENCRYPTED[de199f8d18f3fb0958784265ae5c138de547dc3a17bd2bdd92f788e1855a35256c76f3f2666769c0c2bc380377725234]
  script:
    - git config --global user.email webfolk@csumb.edu
    - git config --global user.name csumbwebfolk
    - git clone --branch gh-pages https://$GITHUB_TOKEN@github.com/csumb/style-guide.git
    - npm run storybookbuild
    - cd style-guide
    - git add *
    - git commit -m "Updated storybook" || true
    - git push origin gh-pages || true