language: node_js
node_js:
  - '8'
before_script:
  - ./node_modules/.bin/grunt
  - npm run test
script:
  - ./node_modules/.bin/gatsby build
  - npm run directoryJson
  - npm run buildJson
  - npm run configFirebase
  - npm run canary
  - ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN -P $TRAVIS_BRANCH
