language: node_js
node_js:
  - '8'
before_script:
  - git clone --depth 1 https://$GITHUB_TOKEN@github.com/csumb/web-data.git _data
  - git clone --depth 1 https://$GITHUB_TOKEN@github.com/csumb/web-content.git _web-content
  - npm run test
script:
  - set -e
  - node --max_old_space_size=12000 ./node_modules/.bin/gatsby build
  - npm run directoryJson
  - npm run scheduleJson
  - npm run eventJson
  - npm run buildJson
  - npm run configFirebase
  - npm run canary
  - cd functions; npm i; cd ..
  - ./node_modules/.bin/firebase deploy --only hosting --token=$FIREBASE_TOKEN -P $TRAVIS_BRANCH -f
