language: node_js
node_js:
  - '8'
cache:
  directories:
    - .firebase
before_script:
  - git clone --depth 1 https://$GITHUB_TOKEN@github.com/csumb/web-data.git _data
  - git clone --depth 1 https://$GITHUB_TOKEN@github.com/csumb/web-content.git _web-content
script:
  - set -e
  - node --max_old_space_size=12000 ./node_modules/.bin/gatsby build
  - npm run directoryJson
  - npm run eventJson
  - npm run catalogJson
  - npm run buildJson
  - npm run canary
  - ./node_modules/.bin/gh-pages -b master -d public -r https://$GITHUB_TOKEN@github.com/csumb-edu/csumb-edu.github.io.git
