language: node_js
node_js:
  - '8'
cache:
  directories:
    - .firebase
before_script:
  - git clone --depth 1 https://$GITHUB_TOKEN@github.com/csumb/website-data.git _data
script:
  - set -e
  - node --max_old_space_size=12000 ./node_modules/.bin/gatsby build
  - npm run canary
  - ./node_modules/.bin/firebase deploy --only hosting --token=$FIREBASE_TOKEN -P $TRAVIS_BRANCH -f
