[[plugins]]
package = "netlify-deployment-hours-plugin"

  [plugins.inputs]
  # A cron-like expression that expresses when a deployment can occur
  expression = "* 5-8 * * *"
  # tz database value that expresses the timezone of the expression
  timezone = "America/Los_Angeles"